### ISSUE TITLE
Vanilla Minecraft Feature Tracking

### ISSUE THREAD

**Issue by IvanCraft623** [IvanCraft623/MobPlugin#36]
Tracking implementation of various vanilla Minecraft mob's features.

#### Animal
- [ ] [Bat](https://minecraft.fandom.com/wiki/Bat)
- [x] [Chicken](https://minecraft.fandom.com/wiki/Chicken)
- [x] [Cow](https://minecraft.fandom.com/wiki/Cow)
- [ ] [Pig](https://minecraft.fandom.com/wiki/Pig)
- [x] [Sheep](https://minecraft.fandom.com/wiki/Sheep)
- [x] [Squid](https://minecraft.fandom.com/wiki/Squid)
#### Monster
- [ ] [Spider](https://minecraft.fandom.com/wiki/Spider)
- [ ] [Cave Spider](https://minecraft.fandom.com/wiki/Cave_Spider)
- [ ] [Enderman](https://minecraft.fandom.com/wiki/Enderman)
- [ ] [Zombie](https://minecraft.fandom.com/wiki/Zombie)
- [x] [Creeper](https://minecraft.fandom.com/wiki/Creeper)
- [x] [Endermite](https://minecraft.fandom.com/wiki/Endermite)
- [ ] [Skeleton](https://minecraft.fandom.com/wiki/Skeleton)
- [ ] [Slime](https://minecraft.fandom.com/wiki/Slime)

#### Animal
- [ ] [Axolotl](https://minecraft.fandom.com/wiki/Axolotl)
- [ ] [Bee](https://minecraft.fandom.com/wiki/Bee)
- [ ] [Camel](https://minecraft.fandom.com/wiki/Camel)
- [ ] [Cat](https://minecraft.fandom.com/wiki/Cat)
- [ ] [Cod](https://minecraft.fandom.com/wiki/Cod)
- [ ] [Donkey](https://minecraft.fandom.com/wiki/Donkey)
- [ ] [Fox](https://minecraft.fandom.com/wiki/Fox)
- [ ] [Frog](https://minecraft.fandom.com/wiki/Frog)
- [ ] [Horse](https://minecraft.fandom.com/wiki/Horse)
- [x] [Mooshroom](https://minecraft.fandom.com/wiki/Mooshroom)
- [ ] [Mule](https://minecraft.fandom.com/wiki/Mule)
- [ ] [Ocelot](https://minecraft.fandom.com/wiki/Ocelot)
- [ ] [Parrot](https://minecraft.fandom.com/wiki/Parrot)
- [ ] [Pufferfish](https://minecraft.fandom.com/wiki/Pufferfish)
- [ ] [Rabbit](https://minecraft.fandom.com/wiki/Rabbit)
- [ ] [Salmon](https://minecraft.fandom.com/wiki/Salmon)
- [ ] [Glow Squid](https://minecraft.fandom.com/wiki/Glow_Squid)
- [ ] [Strider](https://minecraft.fandom.com/wiki/Strider)
- [ ] [Tadpole](https://minecraft.fandom.com/wiki/Tadpole)
- [ ] [Tropical Fish](https://minecraft.fandom.com/wiki/Tropical_Fish)
- [ ] [Turtle](https://minecraft.fandom.com/wiki/Turtle)
- [ ] [Sniffer](https://minecraft.fandom.com/wiki/Sniffer)
- [ ] [Dolphin](https://minecraft.fandom.com/wiki/Dolphin)
- [ ] [Goat](https://minecraft.fandom.com/wiki/Goat)
- [ ] [Llama](https://minecraft.fandom.com/wiki/Llama)
- [ ] [Panda](https://minecraft.fandom.com/wiki/Panda)
- [ ] [Polar Bear](https://minecraft.fandom.com/wiki/Polar_Bear)
- [ ] [Wolf](https://minecraft.fandom.com/wiki/Wolf)
- [ ] [Hoglin](https://minecraft.fandom.com/wiki/Hoglin)
#### Monster
- [ ] [Piglin](https://minecraft.fandom.com/wiki/Piglin)
- [ ] [Zombified Piglin](https://minecraft.fandom.com/wiki/Zombified_Piglin)
- [ ] [Blaze](https://minecraft.fandom.com/wiki/Blaze)
- [ ] [Zombie Villager](https://minecraft.fandom.com/wiki/Zombie_Villager)
- [ ] [Drowned](https://minecraft.fandom.com/wiki/Drowned)
- [ ] [Husk](https://minecraft.fandom.com/wiki/Husk)
- [ ] [Guardian](https://minecraft.fandom.com/wiki/Guardian)
- [ ] [Elder Guardian](https://minecraft.fandom.com/wiki/Elder_Guardian)
- [ ] [Stray](https://minecraft.fandom.com/wiki/Stray)
- [ ] [Wither_Skeleton](https://minecraft.fandom.com/wiki/Wither_Skeleton)
- [ ] [Pillager](https://minecraft.fandom.com/wiki/Pillager)
- [ ] [Vindicator](https://minecraft.fandom.com/wiki/Vindicator)
- [ ] [Evoker](https://minecraft.fandom.com/wiki/Evoker)
- [ ] [Vex](https://minecraft.fandom.com/wiki/Vex)
- [ ] [Ravager](https://minecraft.fandom.com/wiki/Ravager)
- [ ] [Witch](https://minecraft.fandom.com/wiki/Witch)
- [ ] [Ghast](https://minecraft.fandom.com/wiki/Ghast)
- [ ] [Magma Cube](https://minecraft.fandom.com/wiki/Magma_Cube)
- [ ] [Zoglin](https://minecraft.fandom.com/wiki/Zoglin)
- [ ] [Phantom](https://minecraft.fandom.com/wiki/Phantom)
- [ ] [Shulker](https://minecraft.fandom.com/wiki/Shulker)
- [ ] [Silverfish](https://minecraft.fandom.com/wiki/Silverfish)
- [ ] [Piglin Brute](https://minecraft.fandom.com/wiki/Piglin_Brute)
- [ ] [Warden](https://minecraft.fandom.com/wiki/Warden)
#### Boss
- [ ] [Ender Dragon](https://minecraft.fandom.com/wiki/Ender_Dragon)
- [ ] [Wither](https://minecraft.fandom.com/wiki/Wither)
#### Other
- [ ] [Allay](https://minecraft.fandom.com/wiki/Allay)
- [ ] [Skeleton Horse](https://minecraft.fandom.com/wiki/Skeleton_Horse)
- [ ] [Snow Golem](https://minecraft.fandom.com/wiki/Snow_Golem)
- [ ] [Villager](https://minecraft.fandom.com/wiki/Villager)
- [ ] [Wandering Trader](https://minecraft.fandom.com/wiki/Wandering_Trader)
- [ ] [Iron Golem](https://minecraft.fandom.com/wiki/Iron_Golem)

### Other features
- [ ] Mounting
- [ ] [Spawners](https://minecraft.fandom.com/wiki/Monster_Spawner)
- [ ] [Natural spawning](https://minecraft.fandom.com/wiki/Spawn#Bedrock_Edition)
- [x] [Natural despawning](https://minecraft.fandom.com/wiki/Spawn#Bedrock_Edition_2)
- [ ] [`/summon` command](https://minecraft.fandom.com/wiki/Commands/summon)
